fieldLayouts:
  b4374741-f4e6-4b09-87ee-b9df5b123d9c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec847d74-e50a-4e2b-a952-3cce4c2460c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a3fef46-0088-4b09-866c-161e61b30552 # Explanation Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4feb0ef-b37d-4115-a612-e22488e3175a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 921f70f4-0da8-4196-b2e8-c0945c447931 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64ad2a6a-5d13-4f4c-83e6-d5f2c97ff731
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 014a41f5-5d2f-4382-a3c0-a432fcff59f5
        userCondition: null
handle: explanations
hasTitleField: false
name: Explanations
section: 1e3f01ed-f078-413d-8145-6a4e150c6fd9 # Explanations
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: Explanations
titleTranslationKeyFormat: null
titleTranslationMethod: site
