fieldLayouts:
  f9ef133a-b731-4ebb-95fa-fecfd444f620:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 37ba9787-5286-4dda-9f2e-532812adb7cb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 430a43b0-dd6f-46d4-a99e-270573bdef2e
        userCondition: null
fs: images
handle: cars
name: Cars
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
