fieldLayouts:
  b0b9bafd-c275-4310-b2ee-0a7993086a12:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0b3e3e55-5b2d-450c-ad88-a02a90ae2553
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c50b661-b67c-4dd9-b19d-c5067590cccc
        userCondition: null
fs: explanations
handle: explanations
name: Explanations
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
