fieldLayouts:
  462952c5-fde0-4628-a297-c5800f4152c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 42da651b-7fba-4da9-9370-ef1d5638310b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4787ea46-cff4-47be-852d-fba0d0b97de9
        userCondition: null
fs: head
handle: header
name: Head
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
