columnSuffix: adfebfqo
contentColumnType: integer(10)
fieldGroup: a499a58e-dc1f-4e8a-86e0-0d9528e74362 # Cars
handle: price
instructions: 'Determine the selling price'
name: Price
searchable: false
settings:
  currency: EUR
  defaultValue: 0
  max: null
  min: 0
  showCurrency: true
  size: 10
translationKeyFormat: null
translationMethod: none
type: craft\fields\Money
