defaultPlacement: end
enableVersioning: true
handle: cars
name: Cars
propagationMethod: all
siteSettings:
  5349bc07-fc60-4543-bfb1-2aee4768fb33: # examenandres
    enabledByDefault: true
    hasUrls: true
    template: food/_entry.twig
    uriFormat: 'food/{slug}'
type: channel
